/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    "user-validations": UserValidation;
    conversations: Conversation;
    "message-reactions": MessageReaction;
    transactions: Transaction;
    "user-points": UserPoint;
    workflows: Workflow;
    pointTransferLogs: PointTransferLog;
    media: Media;
    "lora-categories": LoraCategory;
    "lora-models": LoraModel;
    "published-posts": PublishedPost;
    "published-images": PublishedImage;
    "generated-images": GeneratedImage;
    "image-reactions": ImageReaction;
    "user-favorites": UserFavorite;
    "payload-preferences": PayloadPreference;
    "payload-migrations": PayloadMigration;
  };
  globals: {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  username?: string | null;
  bio?: string | null;
  avatar?: string | Media | null;
  authProvider: "local" | "google" | "facebook" | "x";
  sub?: string | null;
  roles?: ("admin" | "user")[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-validations".
 */
export interface UserValidation {
  id: string;
  user: string | User;
  code?: string | null;
  expiresAt?: string | null;
  isUsed?: boolean | null;
  updatedAt: string;
  createdAt: string;
}

export interface ImageData {
  url: string;
  id: string;
  reactions: {
    likes: number;
    dislikes: number;
  };
  userReaction: {
    like: boolean;
    dislike: boolean;
    comment?: string;
  };
}

export interface ConversationData {
  conversation: Conversation;
  currentBranch: Branch[];
  lora?: LoraModel;
}

export interface Branch {
  id: string;
  index: number;
  role: string;
  content: Content[];
  timestamp: string;
  status: string;
  parentId: string | null;
  childrenIds: string[];
  progress?: string;
}

export interface Content {
  index: number;
  text: string;
  loadingMessage?: string;
  images?: ImageData[];
  model?: string;
}

export interface Message {
  id: string;
  index: number;
  role: "user" | "assistant" | "system";
  content: Content[];
  timestamp: string;
  status: "pending" | "failed" | "active";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversations".
 */
export interface Conversation {
  id: string;
  user: string | User;
  title: string;
  is_favorite?: boolean | null;
  messages:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  structure: {
    messageId: string;
    childrenIds?:
      | {
          id?: string | null;
        }[]
      | null;
    parentId?: string | null;
    id?: string | null;
  }[];
  currentNodeId: string;
  status: "active" | "deleted";
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  lastMessageAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "message-reactions".
 */
export interface MessageReaction {
  id: string;
  user: string | User;
  like?: boolean | null;
  comment?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: string;
  user: string | User;
  transactionId: string;
  amount: number;
  currency: string;
  status: "Completed" | "Pending" | "Refunded";
  timestamp: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-points".
 */
export interface UserPoint {
  id: string;
  user: string | User;
  points: number;
  extraPoints?: number;
  pointType?: "PLUS" | "PAYG" | "FREE";
  expireAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workflows".
 */
export interface Workflow {
  id: string;
  name: string;
  serviceName: string;
  directions: string;
  cost: number;
  desc?: string | null;
  cover?: string | Media | null;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  caption?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pointTransferLogs".
 */
export interface PointTransferLog {
  id: string;
  user: string | User;
  workflow?: (string | null) | Workflow;
  event: string;
  status: string;
  amount: number;
  beforePoints: number;
  afterPoints?: number | null;
  jobId?: string | null;
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lora-categories".
 */
export interface LoraCategory {
  id: string;
  name: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lora-models".
 */
export interface LoraModel {
  canImageToImage: boolean;
  id: string;
  title: string;
  value: string;
  loraCategories?: (string | null) | LoraCategory;
  cover?: string | Media | null;
  description?: string | null;
  reference?: (string | PublishedImage)[] | null;
  basicSettings?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  trainingParams?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  workflow?: (string | null) | Workflow;
  authors?: (string | User)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "published-posts".
 */
export interface PublishedPost {
  id: string;
  title: string;
  description?: string | null;
  user: string | User;
  publishedImages?: (string | PublishedImage)[] | null;
  messageId?: string | null;
  contentIndex?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "published-images".
 */
export interface PublishedImage {
  id: string;
  pointTransferLogs: string | PointTransferLog;
  user: string | User;
  url: string;
  is_published?: boolean | null;
  shortId?: string;
  reactions?:
    | {
        type: "like" | "dislike";
        count: number;
        id?: string | null;
      }[]
    | null;
  userReaction: { like: boolean; dislike: boolean; comment: string };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "generated-images".
 */
export interface GeneratedImage {
  id: string;
  user?: (string | null) | User;
  pointTransferLogs: string | PointTransferLog;
  loraModel?: (string | null) | LoraModel;
  userMessage?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  workflowData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "image-reactions".
 */
export interface ImageReaction {
  id: string;
  publishedImage: string | PublishedImage;
  user: string | User;
  reactions?: {
    like?: boolean | null;
    dislike?: boolean | null;
  };
  comment?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-favorites".
 */
export interface UserFavorite {
  id: string;
  publishedImage: string | PublishedImage;
  user: string | User;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: "users";
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tasks".
 */
export interface Task {
  id: string;
  status:
    | "IN_QUEUE"
    | "PROMPT_DELIVERING"
    | "AI_PROCESSING"
    | "GENERATING"
    | "COMPLETED"
    | "FAILED"
    | "RETRY";
  prompt: string;
  loraModel: (string | null) | LoraModel;
  /**
   * 外部任务系统的ID
   */
  jobId?: string | null;
  workflow?: (string | null) | Workflow;
  publishedImages?: (string | PublishedImage)[] | null;
  images: [{
    file?: File;
    name?: string;
    url?: string; // 從 API 獲取的原圖 URL
  }];
  user: {
    relationTo: "users";
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
